apiVersion: v1
kind: Service
metadata:
  name: appsvc1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    #targetPort: 80
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: appsvc2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    #targetPort: 80
  selector:
    app: app2
