---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-ep
spec:
  ports:
    - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-ep
subsets:
  - addresses:
      ## minikube
      #- ip: 192.168.39.1
      ## vagrant
      #- ip: 192.168.32.10
      # gce
      - ip: 10.132.0.19
    ports:
      - port: 1
