apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      volumes:
        - name: myspace
          persistentVolumeClaim:
            claimName: nginx-pvc
      containers:
        - image: nginx:1.15
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: myspace
      restartPolicy: Always
status: {}
