apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
