---
- hosts: masters
  gather_facts: false
  tasks:
    - name: apply kubernetes yaml files
      shell: "{{ item }}"
      args:
        chdir: /vagrant
      with_items:
        #- "make ingress_nginx"
        #- "make metallb_system"
        - "make glusterv_apply"
