---
- hosts:
    - haproxy
    - masters
  tasks:
    - name: deploy git code to instances
      become: yes
      git:
        repo: 'https://github.com/carlessanagustin/k8s_example'
        dest: /opt/k8s_example
        version: HEAD
        clone: yes
        update: yes
        accept_hostkey: yes
        force: yes

- hosts: masters
  tasks:
    - name: deploy k8s app
      tags: deploy
      shell: "{{ item}}"
      args:
        chdir: /opt/k8s_example
      with_items:
        ## 2 apps
        #- "make app_apply"
        # 1 apps + gluster
        - "make glusterv_apply"

- hosts: haproxy
  tasks:
    - name: TODO - add published port to haproxy.cfg
      when: False
      template:
        src: ../templates/haproxy.cfg.j2
        dest: /opt/k8s_example/lb-haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: TODO - start HA proxy server
      when: False
      args:
        chdir: /opt/k8s_example
      shell: "{{ item}}"
      with_items:
        - "make haproxy_up"
