---
- hosts:
    - gluster
    - masters
  gather_facts: no
  vars_files:
    - ./private.yml
  tasks:
    - name: copy git_key_file to remote
      tags: git
      copy:
        src: "{{ git_key_file }}"
        dest: git_key_file
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
        force: yes

    - name: deploy git code to instances
      tags: git
      become: yes
      git:
        repo: "{{ item.git_repo }}"
        dest: "{{ item.git_dest }}"
        version: "{{ item.git_version | default('HEAD') }}"
        key_file: "/home/{{ ansible_user }}/{{ item.git_key_file | default(omit) }}"
        clone: yes
        update: yes
        accept_hostkey: yes
        force: yes
      with_items: "{{ deploy_code_repo_list }}"

    - name: delete git_key_file from remote
      tags: git
      file:
        path: git_key_file
        state: absent
        force: yes

    - name: customize deployment
      tags: customize
      shell: "{{ item}}"
      args:
        chdir: /opt/k8s_example
      with_items:
        - "sudo sed -i 's|<glusterfs_ip>|{{ GSERVER_IP }}|g' ./pv-glusterfs/ep-glusterfs.yaml"

- hosts: masters
  tasks:
    - name: deploy k8s app
      tags: deploy
      shell: "{{ item}}"
      args:
        chdir: /opt/k8s_example
      with_items:
        ## 2 apps
        #- "make app_apply"
        # 1 apps + gluster
        - "make glusterv_apply"

- hosts: haproxy
  tasks:
    - name: TODO - add published port to haproxy.cfg
      when: False
      template:
        src: ../templates/haproxy.cfg.j2
        dest: /opt/k8s_example/lb-haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: TODO - start HA proxy server
      when: False
      args:
        chdir: /opt/k8s_example
      shell: "{{ item}}"
      with_items:
        - "make haproxy_up"
