---
## gce_machine_type...
## Machine name - Virtual CPUs	- Memory (GB)
## f1-micro - 0.2 - 0.60
## g1-small - 0.5 - 1.70
## n1-standard-1 - 1 - 3.75
## n1-standard-2 - 2 - 7.50

## custom gce_machine_type...
## zones/[ZONE]/machineTypes/custom-NUMBER_OF_CPUS-AMOUNT_OF_MEMORY
## zones/europe-west4-b/machineTypes/custom-4-8192

## gce_image...
## ubuntu-1604
## ubuntu-1404

- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    gce_image: ubuntu-1604
    gce_disk_size: 20
    gce_zone: europe-west1-b
    # service account must have roles: iam.serviceAccountUser + compute.admin
    gce_service_account_email: csanagustin@engineering-test-197116.iam.gserviceaccount.com
    gce_credentials_file: ~/keys/engineering-test-197116-c121bfb4e36b.json
    gce_project_id: engineering-test-197116
  tasks:
    - name: Launch instances
      gce:
          instance_names: "{{ item.gce_instance_name }}"
          machine_type: "{{ item.gce_machine_type }}"
          image: "{{ gce_image }}"
          disk_size: "{{ gce_disk_size }}"
          project_id: "{{ gce_project_id }}"
          tags: "{{ item.gce_tags | default(omit) }}"
          zone: "{{ gce_zone }}"
          state: present
          service_account_email: "{{ gce_service_account_email }}"
          credentials_file: "{{ gce_credentials_file }}"
      register: gce_instance
      with_items:
        - { gce_instance_name: 'k8s-test-master-001', gce_machine_type: 'n1-standard-1'}
        - { gce_instance_name: 'k8s-test-worker-001', gce_machine_type: 'n1-standard-1'}
        - { gce_instance_name: 'k8s-test-worker-002', gce_machine_type: 'n1-standard-1'}
        - { gce_instance_name: 'k8s-test-haproxy-001', gce_machine_type: 'g1-small', gce_tags: 'http-server,https-server'}
        - { gce_instance_name: 'k8s-test-gluster-001', gce_machine_type: 'g1-small'}
