---
- hosts: masters
  tasks:
    - name: Debian - install glusterfs server
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        package: wget
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - wget

    - name: TODO - configuring gluster
      shell: "{{ item}}"
      with_items:
        - 'wget https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz'
        - 'tar -zxvf helm-v2.11.0-linux-amd64.tar.gz'
        - 'sudo cp linux-amd64/helm /usr/local/bin/'
        - 'helm init'
        - 'helm repo update'
        #- 'helm install stable/nginx-ingress --name nginx-ingress-controller'

# kubectl create clusterrolebinding add-on-cluster-admin     \
#   --clusterrole=cluster-admin     \
#   --serviceaccount=kube-system:default
#
# kubectl create clusterrolebinding add-on-cluster-admin \
#   --clusterrole=cluster-admin \
#   --serviceaccount=kube-system:default \
#   -n kube-system
#
# helm init --tiller-namespace kube-system
# helm init --tiller-namespace default
#
# helm reset --tiller-namespace kube-system --force
# helm reset --tiller-namespace default --force
#
# kubectl delete clusterrolebinding add-on-cluster-admin -n kube-system
# kubectl delete clusterrolebinding add-on-cluster-admin -n default
# ---
# kubectl create serviceaccount --namespace kube-system tiller
# kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
# kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
# ---
# helm install stable/kubernetes-dashboard
