---
- hosts: all
  vars:
    GSERVER: 'gserver'
    #GSERVER_IP: '192.168.32.10'
  tasks:
    - name: Debian - install glusterfs client
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        package: glusterfs-client
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: adding gluster server to /etc/hosts
      become: yes
      lineinfile:
        path: /etc/hosts
        regexp: '^{{ GSERVER_IP }}'
        line: '{{ GSERVER_IP }}    {{ GSERVER }}'

- hosts: gluster
  tasks:
    - name: Debian - install glusterfs server
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        package: glusterfs-server
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Configuring gluster server
      become: yes
      shell: "{{ item}}"
      with_items:
        - 'sed -i "s|^127.0.0.1.*|& $GSERVER|m" /etc/hosts'
        - 'mkdir -p $S_FOLDER'
        - 'gluster volume create $GNAME $GSERVER:$S_FOLDER force'
        - 'gluster volume start $GNAME'
        - 'echo "This is a GLUSTERFS test" > $S_FOLDER/index.html'
      environment:
        S_FOLDER: '/tmp/gfs'
        GNAME: 'gfs'
        GSERVER: 'gserver'

# test: mkdir /tmp/gfs && sudo mount -t glusterfs gserver:/gfs /tmp/gfs
