---
- hosts: masters
  name: Setup k8s worker node
  gather_facts: false
  tasks:
    - name: get k8s join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - name: join k8s cluster
      shell: "{{ item }}"
      with_items:
        - "sudo modprobe -- ip_vs"
        - "sudo modprobe -- ip_vs_rr"
        - "sudo modprobe -- ip_vs_wrr"
        - "sudo modprobe -- ip_vs_sh"
        - "{{ hostvars['master1'].join_command }} >> $HOME/node_joined.txt"
        - "sleep 10"
