# more: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

---
- hosts: masters
  vars:
    pod_network: flannel
    # pod_network: flannel | calico (untested)
    api_advertise: '--apiserver-advertise-address=192.168.32.11'
  tasks:
    - name: flannel - setting pod network cidr
      when: pod_network == "flannel"
      become: yes
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 {{ api_advertise }} >> $HOME/cluster_initialized.txt"

    - name: calico - setting pod network cidr
      when: pod_network == "calico"
      become: yes
      shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 {{ api_advertise }} >> $HOME/cluster_initialized.txt"

    - name: setting up network
      shell: "{{ item }}"
      with_items:
        - "mkdir -p $HOME/.kube"
        - "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: flannel - deploy a pod network to the cluster
      when: pod_network == "flannel"
      shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml >> $HOME/pod_network_setup.txt"

    - name: calico - deploy a pod network to the cluster
      when: pod_network == "calico"
      shell: "{{ item }}"
      with_items:
        - "kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml"
        - "kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml"
